name: brushwire

services:
  database:
    image: postgres
    restart: always
    ports: 
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=brushwire
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - postgres_data:/apps/postgres:/var/lib/postgresql/data

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - node_modules:/backend/node_modules
      - backend_files:/backend/files
    logging:
      driver: none
    depends_on:
      - database


volumes:
  node_modules: 
    driver: local
  backend_files:
    driver: local
  postgres_data:
    driver: local